"""add last_synced_at to github_installations

Revision ID: ab749b0da17f
Revises: 0ee4b7378fb1
Create Date: 2026-08-08 14:31:54.877527
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab749b0da17f'
down_revision: Union[str, None] = '0ee4b7378fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_installations', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_installations', 'last_synced_at')
    # ### end Alembic commands ###
